server:
  port: 10001 #定义端口
eureka:
  instance:
    hostname: eureka-server
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-server:10001/eureka