server:
  port: 10003 #定义端口
spring:
  application:
    name: consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka

  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${random.value}